saml:
  image: tozny/simplesaml:tozny
  volumes:
    - ./params.yml:/params.yml

php:
  image: php:fpm-alpine
  volumes_from:
    - saml
  expose:
    - 9000

web:
  image: nginx:alpine
  ports:
    - "8090:80"
  volumes:
    - ./site.conf:/etc/nginx/conf.d/default.conf
  volumes_from:
    - saml
  links:
    - php