saml:
  image: tozny/simplesamlphp
  volumes:
    - ./params.yml:/params.yml

php:
  image: php:fpm-alpine
  volumes_from:
    - saml
  expose:
    - 9000

web:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ./site.conf:/etc/nginx/conf.d/default.conf
  volumes_from:
    - saml
  links:
    - php